Error: this is my error
   at throwException (longcallstackthrow.js:29:5)
   at throwExceptionWithCatch (longcallstackthrow.js:17:9)
   at Anonymous function (longcallstackthrow.js:40:17)
   at Anonymous function (longcallstackthrow.js:42:13)
   at Anonymous function (longcallstackthrow.js:42:13)
   at Anonymous function (longcallstackthrow.js:42:13)
   at Anonymous function (longcallstackthrow.js:42:13)
   at Anonymous function (longcallstackthrow.js:42:13)
   at Anonymous function (longcallstackthrow.js:42:13)
   at Anonymous function (longcallstackthrow.js:42:13)
