Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at runtest (LongCallStackThrow.js:51:5)
   at function2 (LongCallStackThrow.html:8:5)
   at function1 (LongCallStackThrow.html:13:5)
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
