-- Parent Error.stackTraceLimit: 5, child Error.stackTraceLimit: 10
-- Parent
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
-- Child
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)

-- Parent Error.stackTraceLimit: 5, child Error.stackTraceLimit: Infinity
-- Parent
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
-- Child
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at runtest (LongCallStackThrow.js:51:5)
   at doCalls (StackTraceLimitParent.html:13:5)
   at test (StackTraceLimitParent.html:24:5)
   at onload (StackTraceLimitParent.html:3:15)

-- Parent Error.stackTraceLimit: Infinity, child Error.stackTraceLimit: 3
-- Parent
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at Anonymous function (LongCallStackThrow.js:42:13)
   at runtest (LongCallStackThrow.js:51:5)
   at doCalls (StackTraceLimitParent.html:11:5)
   at test (StackTraceLimitParent.html:28:5)
   at onload (StackTraceLimitParent.html:3:15)
-- Child
Error: this is my error
   at throwException (LongCallStackThrow.js:29:5)
   at throwExceptionWithCatch (LongCallStackThrow.js:17:9)
   at Anonymous function (LongCallStackThrow.js:40:17)

