

Running StackTraceInline Tests

    Executing: 
	    function g(x) {
                f(null, undefined, NaN, true, 1, 'a', { as: 3 }, 23.23, 1e-4, 1, 1, 1, 1, 1, 1, 1);
            }
            function f(x) {
                throw Error('mm');
            }
            function h() {
                g();
            }
            var s = new String('qqq');
            eval('h(s, 123);');
            

    Uncaught exception:
	Call stack: 
	    f(null, undefined, NaN, boolean, number, string, object, number, number, number, number, number, number, number, number, number)(4, 4)
	    g()(1, 4)
	    h(object, number)(7, 4)
	    eval code(0, 0)
	    Global code(10, 0)


	exInfo.bstrDescription: mm
	expected stack frame count 5, got: 5

PASS: TestOnScriptErrorGetExceptionInfoWithArguments

    Executing: 
	    function a() {
                b(1);
            }
            function b(x, y, z) {
                c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
            }
            function c() {
                d(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);
            }
            function d() {
                e(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20);
            }
            function e() {
                f(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21);
            }
            function f() {
                g(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30);
            }
            function g() {
                h(NaN, null, undefined, 'abacaba', 1, 1.3, 1e5, {}, { a: 4 }, new String('a'), true, NaN, null, undefined, 'abacaba', 1, 1.3, 1e5, {}, { a: 4 }, new String('a'), true);
            }
            function h(a,b,c,d,e,f,g,h,i,j,k,l) {
                throw new Error('Error inside of fucntions with a lot of arguments which has to be displayed');
            }
            a();
            

    Uncaught exception:
	Call stack: 
	    h(NaN, null, undefined, string, number, number, number, object, object, object, boolean, NaN, null, undefined, string, number, number, number, object, object, ...)(22, 4)
	    g(number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, ...)(19, 4)
	    f(number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, ...)(16, 4)
	    e(number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number)(13, 4)
	    d(number, number, number, number, number, number, number, number, number, number, number)(10, 4)
	    c(number, number, number, number, number, number, number, number, number, number)(7, 4)
	    b(number)(4, 4)
	    a()(1, 4)
	    Global code(24, 0)


	exInfo.bstrDescription: Error inside of fucntions with a lot of arguments which has to be displayed
	expected stack frame count 9, got: 9

PASS: TestOnScriptErrorGetExceptionInfoWithArguments2

    Executing: 
	    function f(x) {
                throw new Error('x'); 
            }
            f(3);

    Uncaught exception:
	Call stack: 
	    f(number)(1, 4)
	    Global code(3, 0)


	exInfo.bstrDescription: x
	expected stack frame count 2, got: 2

PASS: TestOnScriptErrorGetExceptionInfoWithArguments3

Total Test Cases  3
Passed:  3
Failed   0


